### ISSUE TITLE
Create a simple logger class (💲 6)

### ISSUE THREAD

**Issue by l3alr0g** [7map/7map#21]
Create a logger class which will be used instead of the classic System.out.println() call.

**Comment by kingussopp** [comment]
I expect it to be ready tomorrow (inchallah)

**Comment by l3alr0g** [comment]
That's good news. Remember to regularly push your commits to the branch. When you are ready (all tests have passed and the overall feature is done) create a pull request from the github desktop app or the in-browser github page, assign yourself, add me as a reviewer and link it to this issue (#21).
Remember, if you experience any difficulties, you can message me on discord.

**Comment by kingussopp** [comment]
Noted ☑️

**Comment by l3alr0g** [comment]
@kingussopp feel free to change the value associated to this issue (I may have under/overestimated it)

**Comment by kingussopp** [comment]
Well, I agree that it doesn't need that much map coins so I think 6 is just perfect. However is it 6/10 or 6/100?

**Comment by l3alr0g** [comment]
It's not really six out of something, it's more of an infinite scale on which you measure difficulty in a relative way. I'd say the best way to do this is to compare your "rating" to the values other people have assigned to similarly difficult tasks.

**Comment by kingussopp** [comment]
Well even though they are unlimited, I think we must have a scale, because I may give a simple feature 600 and a complex one 2000, while you would give the simple one 6 and the complex one 20. We will be both on the right side of things while my velocity will be more pondering than yours. That's why I think that with team data we should regulate the pointing system for more rigorosity.

**Comment by l3alr0g** [comment]
Yea I guess...
You should ask @seba1204, he's the one who actually keeps track of these
